name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up trunk
      uses: jetli/trunk-action@v0.5.0

    - name: set up rust wasm target
      run: rustup target add wasm32-unknown-unknown

    - name: build page
      run: make build

    # - name: checkout gh-pages branch
    #   uses: actions/checkout@v4
    #   with:
    #     ref: gh-pages
    #     path: gh-pages

    # - name: copy build to gh-pages branch
    #   run: cp -r docs/* gh-pages

    - name: upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

    - name: deploy to gh-pages
      uses: actions/deploy-pages@v4
